public class PostalBranchDetails {
    Public String Name{get;set;}
    Public String Description{get;set;}
    Public String BranchType{get;set;}
    Public String DeliveryStatus {get;set;}
    Public String Circle {get;set;}
    Public String District {get;set;}
    Public String Division {get;set;}
    Public String Region {get;set;}
    Public String Block {get;set;}
    Public String State {get;set;}
    Public String Country {get;set;}
    Public String Pincode {get;set;}

}