public class PracticeMap {
  public static void PracticeMapMethod ()
  {    
     List<String> strList = new List<String> {'A','B','C'};
      Set<String> strSet1 = new Set<String>();
      Set<String> strSet2 = new Set<String>();
        strSet1.add('A');
        strSet1.add('B');
        strSet1.add('C');
       strSet1.add('D');
      System.debug('strSet1 size =' + strSet1.size());
     
   
  }
}